const NAMA_SEKOLAH: string = "SMKS Antartika 1 SDA.";
const NAMA_SISWA: string = "Excell Marcely.";
let kelas: string = "X RPL 1.";
const NOMOR_ABSEN: number = 9;
const UMUR: number = 16;
let namaFilm = "interstellar";
let sutradara = "Cristoher Nolan";
let produser = "Emma Thomas";
let ditulisOleh = "Jonatahan Nolan";
let pemeran = "Matthew McConaughey, Annw Hathaway, Jessica Chastain, Micahael Caine";
let penataMusik = "Hanz Zimmer";
let sinematografi  = "Hoyte Van Hoytema";
let distributor = "Pramount Pictures";
let tanggalRilis = "7 November 2014";
let durasi = "169 menit";
let negara = "Amerika Serikat";

console.log(" ===================================================== ");
console.log("              Nama Sekolah  :", NAMA_SEKOLAH);
console.log("              Nama Siswa    :", NAMA_SISWA);
console.log("              Kelas         :", kelas);
console.log("              Umur          :", UMUR);
console.log("------------------------------------------------------");
console.log("              Nama Film     :", namaFilm);
console.log("              Sutradara     :", sutradara);
console.log("              Produser      :", produser);
console.log("              Ditulis Oleh  :", ditulisOleh);
console.log("              Pemeran       :", pemeran);
console.log("              Penata Musik  :", penataMusik);
console.log("              Sinematografi :", sinematografi);
console.log("              Distributor   :", distributor);
console.log("              Tanggal Rilis :", tanggalRilis);
console.log("              Durasi        :", durasi);
console.log("              Negara        :", negara);
console.log(" ===================================================== ");